config/routes.rb
require 'sidekiq/web'

OpenCourts::Application.routes.draw do
  root to: 'static_pages#home'

  resources :courts, only: %i[index show] do
    collection do
      get :suggest

      # TODO rm - unused?
      # get :map
    end
  end

  resources :judges, only: %i[index show] do
    collection { get :suggest }

    # TODO rm - unused?
    # member do
    #   get :curriculum
    #   get :cover_letter
    # end
  end

  resources :hearings, only: %i[index show] do
    collection { get :suggest }

    member do
      # TODO rm - unused?
      # get :resource

      delete :anonymize
    end
  end

  resources :decrees, only: %i[index show] do
    collection { get :suggest }

    member { get :document }
  end

  resources :proceedings, only: %i[index show] do
    collection { get :suggest }
  end

=begin
  resources :selection_procedures, as: :selections, path: :selections, only: [:index, :show] do
    collection do
      get :suggest
    end

    member do
      get :declaration
      get :report
    end

    resources :selection_procedure_candidates, as: :candidates, path: :candidates, only: [] do
      member do
        # TODO rm - unused?
        # get :application
        # get :curriculum

        get :declaration

        # TODO rm - unused?
        # get :motivation_letter
      end
    end
  end
=end

  resources :verification, path: :verify, only: %i[index create]

  devise_for :users

  resource :users, only: [] do
    get :subscriptions
  end

  resources :subscriptions, only: %i[create update destroy]

  match '/search/collapse', to: 'search#collapse'
  match '/404', to: 'errors#show', as: :not_found_error
  match '/500', to: 'errors#show', as: :internal_server_error
  match '/health', to: 'static_pages#health'

  mount Sidekiq::Web, at: '/sidekiq'

  match '/:slug', via: :get, to: 'static_pages#show', as: :static_page
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    set_search_model
    set_collapsed_facets

    @results = @model.search(params.freeze)
    @results.associations = search_associations
    @facets = @results.facets

    set_subscription
  end

  def suggest
    set_search_model

    name, term = params[:facet], params[:term]

    @results = @model.suggest(name, term, params.except(:facet, :term))

    if @results
      facet   = @results.facets[name]
      results = facet.results

      render partial: facet.view[:results] || "facets/#{facet.type}_results", locals: { facet: facet, visible: results.first(10), other: results[10..-1] || [] }
    else
      render nothing: true
    end
  end

  def collapse
    set_search_model
    set_collapsed_facets

    id = params[:facet]

    if @model.facets.find { |facet| facet.id == id }
      params[:collapsed] == 'true' ? @collapsed_facets.add(id) : @collapsed_facets.delete(id)
    end

    render nothing: true
  end

  private

  def set_search_model
    @model = params[:controller].singularize.camelize.constantize
  end

  def set_collapsed_facets
    @collapsed_facets = (session["#{params[:controller]}.collapsed_facets".to_sym] ||= Set.new)
  end

  def set_subscription
    if user_signed_in? && @model.respond_to?(:subscribe)
      query = Query.by_model_and_value(@model, @facets.query_params).first

      if query
        @subscription = Subscription.find_by_user_id_and_query_id(current_user.id, query.id)
      end

      unless @subscription
        @subscription = Subscription.new

        @subscription.query = query || Query.new
      end
    end
  end

  def search_associations
    nil
  end

  helper_method :search_path, :suggest_path

  def search_path(params = {})
    url_for params.merge action: :index
  end

  def suggest_path(params = {})
    url_for params.merge action: :suggest
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def search_form_params(params)
    params.each_pair do |name, value|
      next if value.nil?

      if value.is_a? Array
        value.each { |v| yield "#{name}[]", v }
      else
        yield name, value
      end
    end
  end

  def search_list_tag(results, options = {}, &block)
    content_tag :ol, class: 'search-result-list', start: options[:offset] + 1 do
      results.each &block
    end
  end

  def link_to_search(type, body, options = {})
    url = url_for options[:params].merge(controller: type.to_s.downcase.pluralize, action: :index)

    link_to body, url, options.except(:params)
  end

  def link_to_courts_search(body, options = {})
    link_to_search(:courts, body, options)
  end

  def link_to_judges_search(body, options = {})
    link_to_search(:judges, body, options)
  end

  def link_to_hearings_search(body, options = {})
    link_to_search(:hearings, body, options)
  end

  def link_to_decrees_search(body, options = {})
    link_to_search(:decrees, body, options)
  end

  def link_to_proceedings_search(body, options = {})
    link_to_search(:proceedings, body, options)
  end

  def extract_highlight_tokens(highlights)
    Array.wrap(highlights).map { |text| text.scan(%r{<em>(.*?)</em>}) }.flatten.map(&:downcase).uniq
  end
end

app/views/search/_controls.html.erb
<div class="d-flex flex-wrap align-items-center justify-content-between">
  <h1 class="display-2 text-truncate text-uppercase mr-sm-4 mb-3"><%= yield :title %></h1>
  <div class="btn-toolbar" role="toolbar">
    <% if @facets.query_params.any? %>
      <div class="btn-group btn-group-sm border mr-2 mb-3" role="group">
        <%= link_to t('.reset'), search_path, class: 'btn btn-secondary btn-sm shadow-none border-0', data: track(:search, 'reset', 'text:reset') %>
      </div>
    <% end %>
    <% search_sort_fields @facets.params[:sort], @results.sort_fields do |sort, others| %>
      <div class="btn-group btn-group-sm border mb-3" role="group">
        <div class="btn-group btn-group-sm" role="group">
          <%= button_tag t(".sort.#{@model.to_s.underscore}.#{sort}"), class: 'btn btn-secondary dropdown-toggle shadow-none border-left-0 border-right border-top-0 border-bottom-0', data: { toggle: 'dropdown' }.merge(track :search, 'toggle sort', "text:#{sort.dasherize}"), name: nil, type: 'button' %>
          <div class="dropdown-menu dropdown-menu-sm">
            <% others.each do |other, value| %>
              <%= link_to t(".sort.#{@model.to_s.underscore}.#{other}"), search_path(params.merge(sort: value, order: 'desc')), class: 'dropdown-item', data: track(:search, 'select sort', "sort:#{other.dasherize} text:#{other.dasherize}") %>
            <% end %>
          </div>
        </div>
        <%= link_to icon_tag('arrow-up', size: 12), search_path(params.merge(order: 'asc')), class: 'btn btn-secondary d-flex align-items-center shadow-none border-left border-right-0 border-top-0 border-bottom-0', data: track(:search, 'select sort', "sort:#{sort.dasherize} icon:up") if @facets.params[:order] == :desc %>
        <%= link_to icon_tag('arrow-down', size: 12), search_path(params.merge(order: 'desc')), class: 'btn btn-secondary d-flex align-items-center shadow-none border-left border-right-0 border-top-0 border-bottom-0', data: track(:search, 'select sort', "sort:#{sort.dasherize} icon:down") if @facets.params[:order] == :asc %>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag search_path(l: nil), method: :get, class: 'search-query-form' do %>
  <div class="input-group">
    <%= search_field_tag @facets[:q].name, params[@facets[:q].name], id: nil, class: 'form-control search-query-input', placeholder: t(@facets[:q].key)[:placeholder] %>
    <div class="input-group-append">
      <%= link_to icon_tag('times'), search_path(params.except(@facets[:q].name)), class: 'btn search-query-reset', data: track(:search, 'reset', 'icon:reset') if @facets[:q].active? %>
      <%= button_tag icon_tag('search'), class: 'btn search-query-submit', data: track(:search, 'search'), name: nil, type: 'submit' %>
    </div>
  </div>
  <% search_form_params @facets.params.except(:q).reverse_merge(l: I18n.locale) do |name, value| %>
    <%= hidden_field_tag name, value, id: nil %>
  <% end %>
<% end %>

app/views/search/_index.html.erb
<% content_for :scripts do %>
  <script type="text/javascript">
    $(document).ready(function() { new Search('#search-<%= @model.to_s.underscore.dasherize.pluralize %>', '<%= @model.to_s.underscore %>') })
  </script>
<% end %>

<% # TODO rethink this since the goal here is: %>
<% # for >= LG - facets float left and take only needed space, controls + results float right and fill available space %>
<% # for < LG - full width in order: controls, facets, results %>


<div id="search-<%= @model.to_s.underscore.dasherize.pluralize %>" class="clearfix">
  <div class="float-lg-right col-lg-9 mb-3 mb-lg-4 px-0">
    <%= render 'search/controls' %>
  </div>
  <div class="float-lg-left col-lg-3 mb-5 mb-lg-0 px-0 pr-lg-4">
    <%= render 'search/subscribe' if @model.respond_to? :subscribe %>
    <%= render 'facets/list' %>
  </div>
  <div class="float-lg-right col-lg-9 px-0">
    <%= render 'search/results' %>
  </div>
</div>

app/views/search/_results.html.erb
<% if action_name == 'index' %>
  <h2 class="display-2 text-uppercase d-lg-none mb-3"><%= t '.headline' %></h2>
<% end %>

<% if @results.any? %>
  <%= render "#{params[:controller]}/search/results", results: @results, offset: @results.offset %>
<% else %>
  <div class="alert alert-info mb-0" role="alert">
    <%= t '.no_results' %>
  </div>
<% end %>

<div class="d-flex flex-wrap align-items-center justify-content-between">
  <div class="small text-muted mr-3 mt-4">
    <% if @results.any? %>
      <%= t '.found', count: "#{@results.offset + 1} &ndash; #{[@results.offset + @results.per_page, @results.total_count].min}".html_safe, total: translate_with_count(@results.total_count, :result), time: number_with_delimiter(@results.time) %>
    <% else %>
      <%= t '.not_found', time: number_with_delimiter(@results.time) %>
    <% end %>
  </div>
  <% if @results.any? %>
    <nav class="d-flex align-items-center justify-content-end mt-4">
      <%= paginate @results, window: 4 %>
    </nav>
  <% end %>
</div>

app/views/search/_subscribe.html.erb
<button type="button" class="btn btn-outline-primary w-100 mb-3" data-toggle="modal" data-target="#<%= !user_signed_in? || @subscription.new_record? ? 'create' : 'update' %>_subscription">
  <%= t'.subscribe' %>
</button>

<div id="<%= !user_signed_in? || @subscription.new_record? ? 'create' : 'update' %>_subscription" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title text-uppercase"><%= t '.subscribe' %></h1>
      </div>
      <div class="modal-body">
        <% if user_signed_in? %>
          <p class="text-<%= @subscription.new_record? ? 'primary' : 'info' %>">
            <%= t @subscription.new_record? ? '.introduction' : '.already_subscribed' %>
          </p>
          <p>
            <%= t '.explanation' %>
          </p>
          <%= form_for @subscription, method: @subscription.new_record? ? :post : :put, html: { class: 'form-inline' } do |f| %>
            <%= f.fields_for :query do |q| %>
              <%= q.hidden_field :model, value: @model.to_s %>
              <%= q.hidden_field :value, value: Query.unwrap(@facets.query_params) %>
            <% end %>
            <div class="form-group">
              <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons" role="group">
                <% Period.values.each do |_, period| %>
                  <label class="btn btn-outline-secondary<%= ' active' if @subscription.period == period %>">
                    <%= f.radio_button :period_id, period.id, name: 'period_id', checked: @subscription.period == period, autocomplete: 'off' %>
                    <%= t "period.#{period.name}" %>
                  </label>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= t '.sign_in_required' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <% if user_signed_in? %>
          <% unless @subscription.new_record? %>
            <button type="submit" class="btn btn-outline-primary" form="edit_subscription_<%= @subscription.id %>"><%= t '.update' %></button>
            <button type="button" class="btn btn-outline-danger" onclick="$('#<%= !user_signed_in? || @subscription.new_record? ? 'create' : 'update' %>_subscription').modal('hide')" data-toggle="modal" data-target="#delete_subscription"><%= t '.delete' %></button>
          <% else %>
            <button type="submit" class="btn btn-outline-primary" form="new_subscription"><%= t '.create' %></button>
          <% end %>
        <% else %>
          <%= link_to t('.sign_up'), new_registration_path(:user), class: 'btn btn-outline-primary', role: :button %>
          <%= link_to t('.sign_in'), new_session_path(:user), class: 'btn btn-outline-primary', role: :button %>
        <% end %>
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal"><%= t '.cancel' %></button>
      </div>
    </div>
  </div>
</div>

<% unless !user_signed_in? || @subscription.new_record? %>
  <div id="delete_subscription" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title text-uppercase"><%= t '.are_you_sure' %></h1>
        </div>
        <div class="modal-footer">
          <%= link_to t('.confirm_delete'), @subscription, class: 'btn btn-outline-danger', method: :delete, role: :button %>
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal"><%= t '.cancel' %></button>
        </div>
      </div>
    </div>
  </div>
<% end %>