config/routes.rb
require 'sidekiq/web'

OpenCourts::Application.routes.draw do
  root to: 'static_pages#home'

  resources :courts, only: %i[index show] do
    collection do
      get :suggest

      # TODO rm - unused?
      # get :map
    end
  end

  resources :judges, only: %i[index show] do
    collection { get :suggest }

    # TODO rm - unused?
    # member do
    #   get :curriculum
    #   get :cover_letter
    # end
  end

  resources :hearings, only: %i[index show] do
    collection { get :suggest }

    member do
      # TODO rm - unused?
      # get :resource

      delete :anonymize
    end
  end

  resources :decrees, only: %i[index show] do
    collection { get :suggest }

    member { get :document }
  end

  resources :proceedings, only: %i[index show] do
    collection { get :suggest }
  end

=begin
  resources :selection_procedures, as: :selections, path: :selections, only: [:index, :show] do
    collection do
      get :suggest
    end

    member do
      get :declaration
      get :report
    end

    resources :selection_procedure_candidates, as: :candidates, path: :candidates, only: [] do
      member do
        # TODO rm - unused?
        # get :application
        # get :curriculum

        get :declaration

        # TODO rm - unused?
        # get :motivation_letter
      end
    end
  end
=end

  resources :verification, path: :verify, only: %i[index create]

  devise_for :users

  resource :users, only: [] do
    get :subscriptions
  end

  resources :subscriptions, only: %i[create update destroy]

  match '/search/collapse', to: 'search#collapse'
  match '/404', to: 'errors#show', as: :not_found_error
  match '/500', to: 'errors#show', as: :internal_server_error
  match '/health', to: 'static_pages#health'

  mount Sidekiq::Web, at: '/sidekiq'

  match '/:slug', via: :get, to: 'static_pages#show', as: :static_page
end

app/models/hearing.rb
class Hearing < ActiveRecord::Base
  include Resource::URI
  include Resource::Storage
  include Resource::Subscribable

  include Probe

  include Judge::Matched

  attr_accessible :case_number, :file_number, :date, :room, :special_type, :commencement_date, :selfjudge, :note

  scope :at_court, lambda { |court| where court_id: court }

  scope :during_employment,
        lambda { |employment|
          where(court_id: employment.court).joins(:judgings).merge(Judging.of_judge(employment.judge))
        }

  scope :historical, lambda { where('date <  ?', Time.now) }
  scope :upcoming, lambda { where('date >= ?', Time.now) }

  belongs_to :proceeding

  belongs_to :court
  belongs_to :original_court, class_name: :Court

  has_many :judgings, dependent: :destroy
  has_many :inexact_judgings, class_name: :Judging, conditions: Judging.inexact_conditions

  has_many :judges, through: :judgings
  # TODO replace with scope instead of conditions in Rails >= 4
  has_many :exact_judges,
           through: :judgings,
           source: :judge,
           class_name: :Judge,
           conditions: Judging.exact_conditions,
           order: 'judges.last, judges.middle, judges.first'

  belongs_to :type, class_name: :HearingType, foreign_key: :hearing_type_id
  belongs_to :section, class_name: :HearingSection, foreign_key: :hearing_section_id
  belongs_to :subject, class_name: :HearingSubject, foreign_key: :hearing_subject_id
  belongs_to :form, class_name: :HearingForm, foreign_key: :hearing_form_id

  has_many :proposers, dependent: :destroy
  has_many :opponents, dependent: :destroy
  has_many :defendants, dependent: :destroy

  has_many :accusations, through: :defendants

  before_save :invalidate_caches

  max_paginates_per 100
  paginates_per 20

  mapping do
    map :id

    analyze :case_number
    analyze :file_number
    analyze :date, type: :date
    analyze :room
    analyze :special_type
    analyze :commencement_date, type: :date
    analyze :type, as: lambda { |h| h.type.value if h.type }
    analyze :court, as: lambda { |h| h.court.name if h.court }
    analyze :court_type, as: lambda { |h| h.court.type.value if h.court }
    analyze :judges, as: lambda { |h| h.judge_names }
    analyze :form, as: lambda { |h| h.form.value if h.form }
    analyze :section, as: lambda { |h| h.section.value if h.section }
    analyze :subject, as: lambda { |h| h.subject.value if h.subject }
    analyze :proposers, as: lambda { |h| h.proposers.pluck(:name) }
    analyze :opponents, as: lambda { |h| h.opponents.pluck(:name) }
    analyze :defendants, as: lambda { |h| h.defendants.pluck(:name) }
    analyze :participants, as: lambda { |h| h.opponents.pluck(:name) + h.defendants.pluck(:name) }
    analyze :accusations,
            as: lambda { |h| h.accusations.map { |a| "#{a.value} #{a.paragraphs.pluck(:description).join ' '}" } }

    sort_by :date, :created_at
  end

  facets do
    facet :q, type: :fulltext, field: :all
    facet :type, type: :terms, collapsible: false
    facet :court_type, type: :terms
    facet :court, type: :terms
    facet :subject, type: :terms
    facet :judges, type: :terms
    facet :date, type: :date, interval: :month
    facet :form, type: :terms
    facet :proposers, type: :terms
    facet :participants, type: :terms
    facet :section, type: :terms
    facet :file_number, type: :terms
    facet :case_number, type: :terms
    facet :historical,
          type: :boolean,
          field: :date,
          facet: :date,
          value: lambda { |facet| [Time.now..Time.parse('2038-01-19')] if facet.terms == false }
    facet :exact_date, type: :abstract, field: :date, facet: :date, interval: :month
  end

  def time
    @time ||= date.to_datetime if date
  end

  def judge_names
    @judge_names ||= Judge::Names.of judges
  end

  def historical
    date.past? unless date.nil?
  end

  alias historical? historical

  def has_future_date?
    date - 2.years > Time.now.to_datetime unless date.nil?
  end

  def had_future_date?
    date - 2.years > created_at unless date.nil?
  end

  def unprocessed?
    court.nil? || judgings.none?
  end

  def anonymized?
    anonymized_at.present?
  end

  def invalidate_caches
    @time = @judge_names = nil
  end

  def social_security_case?
    mapper = lambda { |association| association.loaded? ? association.map(&:name) : association.pluck(:name) }

    names = mapper.call(defendants) + mapper.call(opponents) + mapper.call(proposers)
    names.any? { |name| ActiveSupport::Inflector.transliterate(name).downcase.match(/socialna\s+poistovna/) }
  end

  def anonymize!(options = { proposers: true, opponents: true, defendants: true })
    anonymizer =
      lambda do |name|
        a, b = ('A'..'Z').to_a.sample(2)

        "#{a}. #{b}."
      end

    anonymize =
      lambda do |association|
        association.find_each do |record|
          loop do
            name = anonymizer.call(record.name)
            record.name = record.name_unprocessed = name

            break unless association.where('id != ?', record.id).where(name: name).any?
          end

          record.save!
        end
      end

    anonymize.call(opponents) if options[:opponents]
    anonymize.call(proposers) if options[:proposers]
    anonymize.call(defendants) if options[:defendants]

    proceeding&.update_index

    save!
    reload

    update_column(:anonymized_at, updated_at)
  end

  def self.anonymize!
    find_each(&:anonymize!)

    Judge.find_each(&:save!)
    Court.find_each(&:save!)
  end

  def self.anonymize_anonymizable_hearings!
    where('hearings.anonymized_at IS NULL').find_each(&:anonymize!)

    Judge.find_each(&:save!)
    Court.find_each(&:save!)
  end

  storage :resource, JusticeGovSk::Storage::HearingPage, extension: :html do |hearing|
    File.join hearing.type.name.to_s, JusticeGovSk::URL.url_to_path(hearing.uri, :html)
  end
end

app/models/hearing/scoped.rb
module Hearing::Scoped
  extend ActiveSupport::Concern

  def self.to(type)
    ClassMethods.type = type
    self
  end

  module ClassMethods
    def self.type=(type)
      raise unless type.is_a? HearingType
      @@type = type
    end

    def type
      @@type
    end

    private

    def apply
      { conditions: { hearing_type_id: @@type.id } }
    end
  end
end

app/models/hearing_form.rb
class HearingForm < ActiveRecord::Base
  attr_accessible :value

  has_many :hearings

  validates :value, presence: true
end

app/models/hearing_type.rb
class HearingType < ActiveRecord::Base
  include Resource::Enumerable

  attr_accessible :value

  has_many :hearings

  validates :value, presence: true

  value :civil,    'Civilné'
  value :criminal, 'Trestné'
  value :special,  'Špecializovaného trestného súdu'
end

app/controllers/hearings_controller.rb
class HearingsController < SearchController
  def show
    @hearing = Hearing.find(params[:id])

    @type = @hearing.type
    @court = @hearing.court
    @judges = @hearing.judges.order(:last, :middle, :first)

    @proposers = @hearing.proposers.order(:name)
    @opponents = @hearing.opponents.order(:name)
    @defendants = @hearing.defendants.order(:name)

    flash.now[:danger] << t('hearings.show.unprocessed') if @hearing.unprocessed?
    flash.now[:danger] << t('hearings.show.future_date') if @hearing.has_future_date?
    flash.now[:warning] << t('hearings.show.faulty_date') if @hearing.had_future_date?
    flash.now[:warning] << t('hearings.show.anonymized') if @hearing.anonymized?
  end

  # TODO rm - unused?
  #  # def resource
  #   @hearing = Hearing.find(params[:id])
  #
  #   send_file_in @hearing.resource_path, type: 'text/plain'
  # end

  def anonymize
    @hearing = Hearing.find(params[:id])

    return head 404 unless current_user.admin?

    @hearing.anonymize!

    flash[:success] = t('hearings.anonymize.success')

    redirect_to :back
  end

  protected

  include FileHelper

  private

  def search_associations
    # NOTE do not eager load scoped associations after original associations,
    # e.g. :exact_judges has to go before :judges, otherwise scoped association will not be loaded
    %i[form subject exact_judges inexact_judgings judges opponents proposers defendants court]
  end
end

app/helpers/hearings_helper.rb
module HearingsHelper
  def hearing_title(hearing)
    title(*hearing_identifiers(hearing) << hearing_type(hearing.type))
  end

  def hearing_headline(hearing, options = {})
    join_and_truncate hearing_identifiers(hearing), options.reverse_merge(separator: ', ')
  end

  def hearing_type(type)
    case type
    when HearingType.civil    then "#{t 'hearings.type.civil'} #{t 'hearings.common.hearing'}"
    when HearingType.criminal then "#{t 'hearings.type.criminal'} #{t 'hearings.common.hearing'}"
    when HearingType.special  then "#{t('hearings.common.hearing').upcase_first} #{t('hearings.type.special').downcase_first}"
    else
      raise
    end
  end

  def hearing_date(date, options = {}, &block)
    date = date.to_date if date.respond_to?(:hour) && date.hour.zero?

    time_tag date, { format: :long }.merge(options), &block
  end

  private

  def hearing_identifiers(hearing)
    [hearing.form, hearing.subject].reject(&:blank?).map(&:value)
  end
end

app/views/hearings/index.html.erb
<% provide :title, t('.title') %>

<%= render 'search/index' %>

app/views/hearings/show.html.erb
<% provide :title, hearing_title(@hearing) %>

<h1 class="text-uppercase my-4">
  <%= hearing_headline @hearing, limit: 49, tooltip: true %>
  <small class="d-block h6 font-weight-bold mt-2 mb-0">
    <%= t '.hearing' %> <%= t @hearing.historical ? '.past' : '.future' %>
    <%= @hearing.date ? hearing_date(@hearing.date) : t('.unknown') %>
  </small>
</h1>

<div class="row">
  <div class="col-xl-8 mb-0-last">
    <% if @court %>
      <p>
        <%= hearing_type @hearing.type %> <%= t @hearing.historical ? '.took_place' : '.will_take_place' %>
        <%= t '.at_court', court: link_to_court(@court) %><%= s t '.in_room', room: @hearing.room if @hearing.room %>.
      </p>
    <% end %>
    <% if @hearing.original_court %>
      <p><%= t '.original_court' %> &ndash; <%= links_to_court @hearing.original_court %></p>
    <% end %>
    <% if @hearing.section || @hearing.special_type %>
      <p>
        <% if @hearing.section %>
          <%= t '.section' %> &ndash; <%= @hearing.section.value %><%= ', ' if @hearing.special_type %>
        <% end %>
        <% if @hearing.special_type %>
          <%= @hearing.section ? t('.special_type').downcase_first : t('.special_type') %> &ndash; <%= @hearing.special_type %>
        <% end %>
      </p>
    <% end %>
    <% if @hearing.form %>
      <p><%= t '.form' %> &ndash; <%= link_to_hearings_search @hearing.form.value, params: { form: @hearing.form.value } %></p>
    <% end %>
    <% if @hearing.subject %>
      <p><%= t '.subject' %> &ndash; <%= link_to_hearings_search @hearing.subject.value, params: { subject: @hearing.subject.value } %></p>
    <% end %>
    <% if @hearing.commencement_date? %>
      <p><%= t '.commencement_date' %> &ndash; <%= hearing_date @hearing.commencement_date %></p>
    <% end %>
    <% unless @hearing.selfjudge.nil? %>
      <p><%= t '.single_judge' %> &ndash; <%= t('polar')[@hearing.selfjudge] %></p>
    <% end %>
    <% if @hearing.note %>
      <p><%= t '.note' %> &ndash; <%= @hearing.note %></p>
    <% end %>
    <p>
      <%= t '.resource' %> &ndash; <%= link_to t('.document'), @hearing.uri %> <span class="text-muted">(<%= t '.document_note' %>)</span>
    </p>
  </div>

  <div class="col-xl-4">
    <ul class="list-unstyled bg-light border mt-3 mt-xl-0 mb-0 p-3">
      <li class="d-flex justify-content-between mx-2">
        <span class="mr-2"><%= tooltip_tag t('case_number.acronym'), t('case_number.full'), placement: 'left' %>:</span>
        <%= @hearing.case_number ? link_to_hearings_search(@hearing.case_number, class: 'text-truncate', params: { case_number: @hearing.case_number }) : t('case_number.missing') %>
      </li>
      <% if @hearing.original_case_number %>
        <li class="d-flex justify-content-between mx-2">
          <span class="mr-2"><%= tooltip_tag t('original_case_number.acronym'), t('original_case_number.full'), placement: 'left' %>:</span>
          <%= link_to_hearings_search(@hearing.original_case_number, class: 'text-truncate', params: { case_number: @hearing.original_case_number }) %>
        </li>
      <% end %>
      <li class="d-flex justify-content-between mx-2">
        <span class="mr-2"><%= tooltip_tag t('file_number.acronym'), t('file_number.full'), placement: 'left' %>:</span>
        <%= @hearing.file_number ? link_to_hearings_search(@hearing.file_number, class: 'text-truncate', params: { file_number: @hearing.file_number }) : t('file_number.missing') %>
      </li>
    </ul>

    <% if @hearing.proceeding %>
      <%= link_to t('.in_proceeding'), @hearing.proceeding, class: 'btn btn-outline-primary d-block mt-3' %>
    <% end %>

    <% if current_user&.admin? && !@hearing.anonymized? %>
      <%= link_to t('.anonymize'), anonymize_hearing_path(@hearing), class: 'btn btn-outline-danger d-block mt-3', method: :delete %>
    <% end %>
  </div>
</div>

<% if @proposers.any? %>
  <h2 class="h4 text-uppercase mt-4"><%= t '.proposers' %></h2>

  <ul class="list-unstyled">
    <% @proposers.each do |proposer| %>
      <li><%= proposer.name %></li>
    <% end %>
  </ul>
<% end %>

<% if @opponents.any? %>
  <h2 class="h4 text-uppercase mt-4"><%= t '.opponents' %></h2>

  <ul class="list-unstyled">
    <% @opponents.each do |opponent| %>
      <li><%= opponent.name %></li>
    <% end %>
  </ul>
<% end %>

<% if @defendants.any? %>
  <h2 class="h4 text-uppercase mt-4"><%= t '.defendants' %></h2>

  <ul class="list-unstyled">
    <% @defendants.each do |defendant| %>
      <li>
        <%= defendant.name %>
        <% if defendant.accusations.any? %>
          <ul class="list-unstyled ml-3 mb-2">
            <% defendant.accusations.each do |accusation| %>
              <li>
                <% if accusation.paragraphs.any? %>
                  <%= accusation.paragraphs.pluck(:description).join ', ' %>,
                <% end %>
                <%= accusation.value %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if @judges.any? %>
  <h2 class="h4 text-uppercase mt-4"><%= t '.judges' %></h2>

  <% if @judges.chaired.any? %>
    <p>
      <%= t '.chairman' %>
      <% if @judges.chaired.exact.any? %>
        <%= links_to_judges @judges.chaired.exact %>.
      <% else %>
        <%= judge_processed_names @judges.chaired.inexact %>
      <% end %>
    </p>
  <% end %>

  <% if @judges.normal.any? %>
    <p>
      <% if @judges.normal.exact.any? %>
        <%= links_to_judges @judges.normal.exact %>
      <% else %>
        <%= judge_processed_names @judges.normal.inexact %>
      <% end %>
    </p>
  <% end %>
<% end %>

<p class="small text-muted mt-4 mb-0">
  <%= s t '.resource_note.description', document: link_to(t('.resource_note.document'), @hearing.uri), update: time_tag(@hearing.updated_at.to_date, format: :default) %>
  <%= s t '.link_note.description', document: link_to(t('.link_note.document'), @hearing.uri) %>
</p>